### ISSUE TITLE
Never increase the earliest supported version based on Confluence data

### ISSUE THREAD

**Issue by foolip** [mdittmer/mdn-confluence#29]
See https://docs.google.com/document/d/13kpKPN-qdWakN5wIbrF2IgDxfPwGzIsYBkaxy4YYxTs/edit?disco=AAAACHbRJrU by @Elchi3:

> Yes, this part would be nice to get for confluence. (see the Proxy.revocable case). Either we fix confluence, or we add things like P.revocable to a blacklist. Also, if bcd has a lower version number and we know that tools like confluence aren't able to get lower browser versions, trust bcd and do not override.

This makes sense given the methodology we use for deriving Confluence API support.

**Comment by jpmedley** [comment]
I'll update the BCD help text today or Monday.

**Comment by jpmedley** [comment]
Or, I'll update when the PR gets merged.

**Comment by foolip** [comment]
Thanks @jpmedley! Feel free to send a PR ahead of time so we can merge them together.

**Comment by foolip** [comment]
Note that we also have to release to npm somehow.
